/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package xyz.maxton;

import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.Timer;

/**
 *
 * @author Max
 */
public class GamePanel extends javax.swing.JPanel implements MouseListener {
    private RootPanel panel;
    private boolean isPaused;
    private ArrayList<ShapeButton> shapes;
    private long score;
    private int time;
    private Timer timer;
    
    /**
     * Creates new form GamePanel
     */
    public GamePanel(RootPanel panel) {
        this.shapes = new ArrayList<ShapeButton>(10);
        this.panel = panel;
        this.isPaused = false;
        this.time = 45;
        initComponents();
        init();
        panel.repaint();
    }
    
    private void init(){
        addMouseListener(this);
        addButton();
        randomizeAll();
        int delay = 1000; //milliseconds
        ActionListener taskPerformer = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                tick();
            }
        };
        this.timer = new Timer(delay, taskPerformer);
        timer.start();
    }
    
    public void pause(){
        this.isPaused = !this.isPaused;
        if(isPaused){
            this.timeLabel.setText("Paused");
        }
        else{
            this.timeLabel.setText("Time: "+this.time);
        }
    }
    
    public void tick(){
        if(this.isPaused == false){
            this.time -= 1;
            this.timeLabel.setText("Time: "+this.time);
            if(this.time <= 0){
                endGame();
            }
        }
    }
    
    public void endGame(){
        timer.stop();
        timer = null;
        this.panel.postGame(score);
    }
    
    public void addButton(){
        this.shapes.add(new ShapeButton(this).setType((int)(Math.random() * 4 + 1)));
    }
    
    public long getScore(){
        return score;
    }
    
    public void addToScore(long add){
        this.score += add;
        this.scoreLabel.setText(new Long(score).toString());
        this.repaint();
    }
    
    public void addRandomButton(){
        if((int)(Math.random() * 13) == 3){
            this.shapes.add(new ShapeButton(this).setType((int)(Math.random() * 6)));
        }
    }
    
    public void randomizeAll(){
        for(ShapeButton s : shapes){
            s.randomizePosition();
        }
        repaint();
    }
    
    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        for(ShapeButton shape : shapes){
            shape.draw(g);
        }
    }

    @Override
    public void mousePressed(MouseEvent e) {
        if(this.isPaused) return;
        
        //Go through the list *backwards* so that it detects the topmost shape FIRST
        for(int i = shapes.size() - 1; i >= 0; i--){
            if(shapes.get(i).hitTest(e.getX(),e.getY())){
                addRandomButton();
                randomizeAll();
                break;
            }
        }
    }

        
    @Override
    public void mouseClicked(MouseEvent e) { }
    
    @Override
    public void mouseReleased(MouseEvent e) {}

    @Override
    public void mouseEntered(MouseEvent e) {}

    @Override
    public void mouseExited(MouseEvent e) {}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    scoreLabel = new javax.swing.JLabel();
    timeLabel = new javax.swing.JLabel();
    scoreLabel1 = new javax.swing.JLabel();
    jButton1 = new javax.swing.JButton();
    jToggleButton1 = new javax.swing.JToggleButton();

    scoreLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    scoreLabel.setText("0000");

    timeLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    timeLabel.setText("Time: 45");

    scoreLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    scoreLabel1.setText("Score:");

    jButton1.setText("Quit");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    jToggleButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    jToggleButton1.setText("| |");
    jToggleButton1.setMargin(new java.awt.Insets(2, 2, 2, 2));
    jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jToggleButton1ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(scoreLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(scoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(4, 4, 4)
        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(jButton1)
            .addComponent(jToggleButton1)
            .addComponent(timeLabel))
          .addComponent(scoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(layout.createSequentialGroup()
            .addGap(2, 2, 2)
            .addComponent(scoreLabel1)))
        .addContainerGap(457, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        timer.stop();
        panel.mainMenu();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        pause();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JToggleButton jToggleButton1;
  private javax.swing.JLabel scoreLabel;
  private javax.swing.JLabel scoreLabel1;
  private javax.swing.JLabel timeLabel;
  // End of variables declaration//GEN-END:variables
}
